export const BRAND_CONFIG = {
  name: "Skorvia",
  legalName: "Skorvia Intelligence Ltd.",
  domain: "skorvia.com",
  url: "https://skorvia.com",
  slogan: "Next-Gen SEO Intelligence & Answer Engine Optimization",
  description:
    "Enterprise-grade SEO insights, backlink tracking, keyword discovery, site audit automation, and AI/AEO ranking intelligence for growth teams and agencies.",
  supportEmail: "support@skorvia.com",
  contactEmail: "hello@skorvia.com",
  salesEmail: "sales@skorvia.com",
  logoUrl: "/logo.png",
  faviconUrl: "/logo.png",
  colors: {
    primary: "#17199b",
    primaryLight: "#2e32cc",
    primaryDark: "#0e106a",
    secondary: "#0ea5e9",
    accent: "#10b981",
    warning: "#f59e0b",
    danger: "#ef4444",
  },
  socials: {
    twitter: "https://twitter.com/skorvia_hq",
    x: "https://x.com/skorvia_hq",
    linkedin: "https://linkedin.com/company/skorvia",
    github: "https://github.com/skorvia",
    discord: "https://discord.gg/skorvia",
  },
  pricing: {
    currencyDefaults: ["USD", "NGN"] as const,
    annualDiscountPercent: 20,
    tiers: [
      {
        id: "starter",
        name: "Starter",
        badge: "Essential",
        description:
          "Perfect for solo founders, creators, and single-site operators.",
        priceMonthlyUSD: 29,
        priceAnnualUSD: 24,
        priceMonthlyNGN: 35000,
        priceAnnualNGN: 29000,
        features: [
          "5 Tracked Domains",
          "500 Monitored Keywords",
          "5,000 Site Audit Pages / mo",
          "Daily SERP Updates",
          "Core Backlink Explorer",
          "Standard Email Alerts",
        ],
        highlighted: false,
      },
      {
        id: "pro",
        name: "Professional",
        badge: "Most Popular",
        description:
          "For scaling businesses, in-house marketing teams, and growth leads.",
        priceMonthlyUSD: 79,
        priceAnnualUSD: 64,
        priceMonthlyNGN: 95000,
        priceAnnualNGN: 79000,
        features: [
          "20 Tracked Domains",
          "2,500 Monitored Keywords",
          "50,000 Site Audit Pages / mo",
          "AI Search & AEO Rankings (ChatGPT, Perplexity)",
          "Competitor Keyword Gap Analysis",
          "Automated Weekly Email Audits",
          "5-Minute Uptime & SSL Monitors",
          "Priority Customer Support",
        ],
        highlighted: true,
      },
      {
        id: "agency",
        name: "Agency & Scale",
        badge: "Full Power",
        description:
          "Complete power suite for agencies, enterprises, and high-volume teams.",
        priceMonthlyUSD: 199,
        priceAnnualUSD: 159,
        priceMonthlyNGN: 240000,
        priceAnnualNGN: 195000,
        features: [
          "Unlimited Tracked Domains",
          "10,000 Monitored Keywords",
          "250,000 Site Audit Pages / mo",
          "White-Label PDF Reports (Custom Branding)",
          "MCP Agent Server Integration",
          "Instant IndexNow Push API",
          "Unlimited Team Seats & Sub-accounts",
          "Dedicated Account Manager",
        ],
        highlighted: false,
      },
    ],
  },
} as const;

export type BrandConfig = typeof BRAND_CONFIG;
